### ISSUE TITLE
strange log errors

### ISSUE THREAD

**Issue by marcolega** [j-a-n/lovelace-wallpanel#27]
I have several messages like this:

Logger: frontend.js.latest.202208020
Source: components/system_log/__init__.py:227
First occurred: 11:11:13 (6349 occurrences)
Last logged: 11:12:32

https://homeassistant.x.x:8123/hacsfiles/lovelace-wallpanel/wallpanel.js?hacstag=30950641626:936:45 Uncaught TypeError: Cannot read properties of undefined (reading 'bind')

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:102
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:14:53 (3 occurrences)
Last logged: 11:15:19

[547343298480] Error handling message: Unauthorized (unauthorized)
[547376716848] Error handling message: Unauthorized (unauthorized)
[547377195152] Error handling message: Unauthorized (unauthorized)

Moreover I have several login unauthorised error when my wallpanel clients starts.

**Comment by j-a-n** [comment]
Are you using the latest version of the addon?

**Comment by marcolega** [comment]
at the end wallpanel works fine, but my client was banned from homeassistant. If i remove banand reboot homeassistant and clients everything is ok.

**Comment by marcolega** [comment]
yes 3.0

**Comment by marcolega** [comment]
was same in the 2.6

**Comment by marcolega** [comment]
![Screenshot_20220901-121356_Home Assistant](https://user-images.githubusercontent.com/97765943/187890512-7d7e0b80-866f-4c9c-b5b4-474e85687667.jpg)

**Comment by marcolega** [comment]
192.168.2.204 is one of my wallpanel display running on rb pi4 with chromium

**Comment by j-a-n** [comment]
Should be fixed with version 3.1.

**Comment by marcolega** [comment]
I still have problems with last version 3.2. Today I get this log:

Logger: homeassistant.components.http.ban
Source: components/http/ban.py:84
Integration: HTTP (documentation, issues)
First occurred: 12:27:05 (1 occurrences)
Last logged: 12:27:05

Login attempt or request with invalid authentication from 192.168.2.206 (192.168.2.206). Requested URL: '/media/vldnas/Foto/MM/2016/Estate_2016/RDC/DSC_1266.JPG?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI2YzNhNWMwMzQ2NTI0ZTViOGJmMDNjM2M4M2JlNTcwNCIsInBhdGgiOiIvbWVkaWEvdmxkbmFzL0ZvdG8vTU0vMjAxNi9Fc3RhdGVfMjAxNi9SREMvRFNDXzEyNjYuSlBHIiwicGFyYW1zIjp7fSwiaWF0IjoxNjYyMjg3MjE0LCJleHAiOjE2NjIyODcyMjR9.oAjvhTl8DQCMkV8LvVVsZdVyiNUyb5oo7a433Rd9JCM'. (Mozilla/5.0 (X11; CrOS aarch64 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.57 Safari/537.36)

Seem to be a problem when access to my local photo (shared mounted folder). Do you have any ideas?

**Comment by marcolega** [comment]
Could be a problem with the acces token? Is it possible to use a long term token?

**Comment by j-a-n** [comment]
I am not sure what is causing your errors.
The addon creates a [signed path] (https://developers.home-assistant.io/docs/auth_api/#signed-paths) and loads the image from that path. This path expires after a while.
Maybe the image takes too long to load.
With version 3.3 of the addon, the signed path now expires after 30 seconds (previously it was 10 seconds).
Additionally, signed path errors are logged in the browser console.
Please try if it is better with this version.

**Comment by j-a-n** [comment]
@marcolega Is the problem fixed now?

**Comment by marcolega** [comment]
yes, problem disappeared from version 3.3.

**Comment by j-a-n** [comment]
Thanks for the feedback!
