### ISSUE TITLE
hide_toolbar only works on initial view

### ISSUE THREAD

**Issue by mrMetalWood** [j-a-n/lovelace-wallpanel#307]
First, thanks for this project! I love it. So many cool things are possible with this. 

I have the wallpanel setup with this config:

```
wallpanel:
  enabled: false
  profiles:
    device_448dfc81_110ce2c6:
      enabled: true
  profile: device_${browser_id}
  hide_sidebar: true
  hide_toolbar: true
  fullscreen: true
```

The wallpanel is only enabled for my tablet. As recommended I use the `browser_mod` for that. 

It all works fine when the dashboard gets loaded initially in Fully Kiosk Browser. The sidebar and the toolbar are hidden on the tablet.

When I then navigate to a subview on the dashboard, the top toolbar appears (which is necessary and good I guess because otherwise you wouldn't be able to go back). But when I then navigate back to the main view (with the arrow in the top left corner) the top toolbar stays activated and visible. Is this expected behaviour? I would expect that the toolbar would then be hidden again. Not sure if this is fixable or that once any navigation started the toolbar has to be visible for some reason.

The only way to get it working again for me is to refresh the browser or restart FKB.

**Comment by warning939** [comment]
Hi Jan,
Thank you for your project!
I have the same issue, the toolbar appears even if I have this in the config:
wallpanel:
  enabled: true
  hide_sidebar: true
  hide_toolbar: true
  fullscreen: true

**Comment by 3DSBricker** [comment]
I experience the same problem. When I click on a back button which I made with bubble-card and simply navigates to the dashboard URL, the toolbar isn't hidden anymore. When I use the toolbar, it navigates to the view I clicked on, but then it does hide the toolbar.

**Comment by j-a-n** [comment]
Please check if wallpanel 4.33.0 fixes the problem.

**Comment by 3DSBricker** [comment]
Hi, for me it does not fix the issue. Whenever I switch to a different dashboard, wallpanel isn't active. The screensaver doesn't work either. Upon clicking one of the views on the top bar, wallpanel is active again. Embedding wallpanel in the url in the button I use, does not work either. Only reloading the page or switching to a different tab on the top bar works.

**Comment by warning939** [comment]
Hi Jan,
I still have the issue.
Thank you!

**Comment by warning939** [comment]
Hi Jan,

I still have the issue.
Do you need any further log to fix this issue?

Thank you!
Peter

**Comment by warning939** [comment]
That's how I use it:

![Image](https://github.com/user-attachments/assets/de557ee6-484f-46c9-b620-ba52b3bc9d44)

And this is a link to it:
https://homeassistant:8123/smartmirror-fent/fent

**Comment by j-a-n** [comment]
Where is this link defined and how do you it?
Is http**s**:// correct?

**Comment by warning939** [comment]
HA runs in docker (Synology)
Yep, https.
I have the same issue on tablet, desktop browser (Chrome).

**Comment by j-a-n** [comment]
Sorry, I still don't understand the problem.
The title of the problem is “hide_toolbar only works on first view”.
So please explain better what you are doing, what is happening and what you expect to happen.

**Comment by x3n0n10** [comment]
As I'm experiencing the same issue I'll try to explain it as well:
I have a dashboard with two pages. First is the default page (ex. A), second is marked as a subview (ex. B) (therefore it will get a back-button in the toolbar). Page A contains a button that navigates to the page B. When you press that button, the toolbar and sidebar reappear (which is convenient, otherwise you wouldn't be able to go back to the page A). When you press the back button on page B, we will return on page A but the toolbar and sidebar stay visible, even though wallpanel is enabled on that page in the yaml.

Kind of the same story as the initial post, but I hope this clears things up as I'm invested in the solution as well :) Thanks for your time and effort!

**Comment by j-a-n** [comment]
Okay, thanks for the explanation!
Please add the following information:

"Page A contains a button that navigates to page B"
Can you please post the yaml of this button? 

Please open a browser console (F12).
Then click on the button on page A.
The browser console will display a message like:
`Location changed from panel 'lovelace/test' to 'lovelace/subview'`.
Please post this message.

**Comment by x3n0n10** [comment]
tap_action of the button (rest of the button yaml relates to its appearance thus irrelevant):
`tap_action:`
`  action: navigate`
`  navigation_path: /dashboard-panelnext/fuel`

On click of button the following message appears in the console:
`Location changed from panel 'dashboard-panelnext/home' to 'dashboard-panelnext/fuel'`

The toolbars reappear and reveal the back button.

When pressing the back button, the toolbars stay visible when returning to page A.
The back button doesn't trigger the 'location changed' console message like above.

My wallpanel yaml for reference:
`wallpanel:`
  `enabled: true`
  `enabled_on_tabs:`
  `  - home`
  `hide_toolbar: true`
  `hide_sidebar: true`
  `fullscreen: true`
  `idle_time: 0`

**Comment by warning939** [comment]
My issue:
I want to hide the toolbar and the sidebar as well (this is a smart mirror)
I have the following settings, but the bars do not disappear:

wallpanel:
  enabled: true
  **hide_sidebar: true
  hide_toolbar: true**
  fullscreen: true
  idle_time: 0
views:
  - title: Fent
...
...
...


![Image](https://github.com/user-attachments/assets/348379bc-5183-4ecc-a910-f1c683a7a0ea)

**Comment by x3n0n10** [comment]
@warning939 This sounds like the very basic functionality that Wallpanel provides and should always work. Especially because there isn't any navigation happening yet. When you open the browser console, do you even get the `Wallpanel version 4.36.1` line upon loading of the page?

**Comment by warning939** [comment]
Yes, I have the latest. And also cleared the cache, etc.

![Image](https://github.com/user-attachments/assets/78e287a7-08df-497c-820f-1169859ef163)

**Comment by j-a-n** [comment]
@x3n0n10
The issue should be resoved in version 4.37.0.
Please see the new config `hide_toolbar_on_subviews` also.

@warning939
I think it is a general issue with the smart mirror and wallpanel.

**Comment by warning939** [comment]
Thank you for your support.
I still have the issue, I do not how to fix it.

![Image](https://github.com/user-attachments/assets/d6026157-c938-4e1a-9174-a0bfb3618892)

**Comment by j-a-n** [comment]
That is a strange error.
Please try if version 4.38.0 works better.

**Comment by warning939** [comment]
This is the error message in the HA logs:

> Logger: frontend.js.modern.202501092
> Source: components/system_log/__init__.py:331
> First occurred: 07:59:56 (4 occurrences)
> Last logged: 07:59:57
> 
> Uncaught error from Chrome 132.0.0.0 on Windows 10 Error: Failed to get hui-view from customElements /local/wallpanel.js:138:8
> Uncaught error from Chrome 132.0.0.0 on Windows 10 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "masonry-layout" has already been used with this registry window.CustomElementRegistry.define (src/scoped-custom-element-registry.js:44:14) /local/plugins/layout-card.js:47:107
> Uncaught error from Chrome 132.0.0.0 on Windows 10 TypeError: Cannot read properties of undefined (reading 'disconnect') Mt.disconnectedCallback (/local/plugins/layout-card_new.js:13:3317) apply (src/scoped-custom-element-registry.js:262:44) this.shadowRoot!.getElementById (src/panels/lovelace/views/hui-masonry-view.ts:168:11) columnElements.push (src/panels/lovelace/views/hui-masonry-view.ts:198:11) changedProperties.has (src/panels/lovelace/views/hui-masonry-view.ts:155:11) willUpdate (src/reactive-element.ts:1327:13) performUpdate (src/reactive-element.ts:1261:16) scheduleUpdate (src/reactive-element.ts:1233:24)

**Comment by j-a-n** [comment]
Odd. Try clearing the browser cache or restart the device.

**Comment by warning939** [comment]
The same issue. :(

**Comment by warning939** [comment]
I removed all other resources. Now I have only wallpanel, but still the same issue. :(

![Image](https://github.com/user-attachments/assets/c9d6c148-53f3-4793-854f-ae57aee23306)

**Comment by rafareusch** [comment]
Hey guys, I'm not sure I'm having the same issue, but I thinks is related somehow.

I have a main view with buttons to enter a few subviews.
The dashboard has:
`wallpanel:
  enabled: true
  hide_toolbar: true
  idle_time: 0`

Which works fine in the first reload. If I navigate to the subview the top bar appears again presenting the back arrow (Which I like) But when I go back to the main view again the top bar still there, with the non-subview items like menu and search.

I'm missing some configuration?

**Comment by rafareusch** [comment]
> As I'm experiencing the same issue I'll try to explain it as well: I have a dashboard with two pages. First is the default page (ex. A), second is marked as a subview (ex. B) (therefore it will get a back-button in the toolbar). Page A contains a button that navigates to the page B. When you press that button, the toolbar and sidebar reappear (which is convenient, otherwise you wouldn't be able to go back to the page A). When you press the back button on page B, we will return on page A but the toolbar and sidebar stay visible, even though wallpanel is enabled on that page in the yaml.
> 
> Kind of the same story as the initial post, but I hope this clears things up as I'm invested in the solution as well :) Thanks for your time and effort!

Okay so I'm having this exact same issue and can confirm it still happens on 4.40
Also tried the new hide toolbar on sideview configuration without success. 
Have you had any luck?

**Comment by j-a-n** [comment]
Please create a minimal dashboard with which the issue can be reproduced and post the YAML.

**Comment by rafareusch** [comment]
Okay so I got the step by step, basically the issue is when you navigate to another dashboard and comes back from it.

Heres an example:


Dashboard 1 (home)

`
wallpanel:
  enabled: true
  hide_toolbar: true
  idle_time: 0
  hide_toolbar_on_subviews: true
views:
  - type: masonry
    title: home
    path: home
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: navigate
          navigation_path: /dashboard-wallpaneltest2/0
        name: GO TO SUBVIEW

`

Dashboard 2
`
views:
  - title: SUBVIEW TEST
    type: sections
    max_columns: 4
    subview: true
    sections:
      - type: grid
        cards:
          - type: heading
            heading: New section
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            name: LIGHT SUBVIEW
            icon: mdi:alarm-light

`


When you go back from Subview, the topbar on the home reappears

**Comment by rafareusch** [comment]
Just to context, yes, the URL /dashboard-wallpaneltest2/0 is correct.

**Comment by j-a-n** [comment]
The example works for me.
Are you sure you are using the latest version 4.40.0?
Please check the browser console for the wallpanel version.

**Comment by j-a-n** [comment]
Which browser / app are you using?

**Comment by rafareusch** [comment]
> Which browser / app are you using?

Chrome on MACOS
iPhone IOS 18 HomeAssistant APP
Samsung Tab A8 with Fully Kiosk 

All of them have the same issue

**Comment by rafareusch** [comment]
> The example works for me. Are you sure you are using the latest version 4.40.0? Please check the browser console for the wallpanel version.

<img width="864" alt="Image" src="https://github.com/user-attachments/assets/96ae5205-9746-4540-af69-cf455442083c" />

**Comment by rafareusch** [comment]
> The example works for me. Are you sure you are using the latest version 4.40.0? Please check the browser console for the wallpanel version.

What HA version are you using? 
when you enter the subview, the top bar is shown or not?
Makes any difference if you use the back arrow from top bar or back arrow from the browser?

**Comment by j-a-n** [comment]
> What HA version are you using?
2025.2.0

>when you enter the subview, the top bar is shown or not?
The top bar is shown in the subview.

> Makes any difference if you use the back arrow from top bar or back arrow from the browser?
No

> You sure your are entering the subview on the other dashboard?
Yes

Could be an timing issue.

**Comment by rafareusch** [comment]
Okay, I have a test server with vastly different configuration that I updated to 2025.2.2 with a fresh install of WallPanel via HACS

Same issue that I described.
I'm happy to hop in a call to help troublshoot something in real time if needed

discord: rafaelreusch

**Comment by j-a-n** [comment]
Just pushed a new wallpanel.js version, but have not released it yet.
Could you please upgrade manually?

- Download [wallpanel.js](https://github.com/j-a-n/lovelace-wallpanel/raw/refs/heads/main/wallpanel.js)
- Place it into config/www/community/lovelace-wallpanel/wallpanel.js
- Make sure you delete the wallpanel.js.gz file if it is in the same directory.
- Open Configuration => Lovelace Dashboards => [Resources](https://my.home-assistant.io/redirect/lovelace_resources/) and add search for `wallpanel.js`.
- Edit the resource
- Change the `hacstag` part of the URL (just change the number to a value that has never been used before)

**Comment by rafareusch** [comment]
> Just pushed a new wallpanel.js version, but have not released it yet. Could you please upgrade manually?
> 
> * Download [wallpanel.js](https://github.com/j-a-n/lovelace-wallpanel/raw/refs/heads/main/wallpanel.js)
> * Place it into config/www/community/lovelace-wallpanel/wallpanel.js
> * Make sure you delete the wallpanel.js.gz file if it is in the same directory.
> * Open Configuration => Lovelace Dashboards => [Resources](https://my.home-assistant.io/redirect/lovelace_resources/) and add search for `wallpanel.js`.
> * Edit the resource
> * Change the `hacstag` part of the URL (just change the number to a value that has never been used before)

Same issue, I confirmed in console it was the version 40.1

**Comment by j-a-n** [comment]
Okay, please add the following to the configuration:
```yaml
wallpanel:
  log_level_console: debug
```
Then open the browser console, reproduce the problem and post the output from the browser console here.

**Comment by rafareusch** [comment]
> Okay, please add the following to the configuration:
> 
> wallpanel:
>   log_level_console: debug
> Then open the browser console, reproduce the problem and post the output from the browser console here.

This console log?

<img width="1173" alt="Image" src="https://github.com/user-attachments/assets/0a263bd4-b867-4f4d-9626-5221576a9461" />

**Comment by rafareusch** [comment]
I don't see any new logs after I navigate and go back, Am I looking at the wrong output?

**Comment by rafareusch** [comment]
Inside both Navigate events

<img width="1142" alt="Image" src="https://github.com/user-attachments/assets/153f9ae5-d494-4d63-8105-71ae55ddd4d9" />

**Comment by j-a-n** [comment]
The output is correct.
The problem is that there are no navigation events when navigating back.

**Comment by rafareusch** [comment]
> The output is correct. The problem is that there are no navigation events when navigating back.

Yeah, and actually, after reproducing the problem, If I go back to the subview, it doesn't send the events either

**Comment by j-a-n** [comment]
Okay, i Think this was just a problem with the logging, because the log level is read to late from the config.
Please manually upgrade to 4.40.2 and repeat the steps to get the log.

**Comment by rafareusch** [comment]
> Okay, i Think this was just a problem with the logging, because the log level is read to late from the config. Please manually upgrade to 4.40.2 and repeat the steps to get the log.

Where I find the .2?

**Comment by j-a-n** [comment]
https://raw.githubusercontent.com/j-a-n/lovelace-wallpanel/refs/heads/main/wallpanel.js

**Comment by rafareusch** [comment]
After doing the process I sitll see 40.1 in the logs, I confirmed that the wallpanel.js is correct inside the folder and edited the hacs tag too, any idea?

**Comment by rafareusch** [comment]
<img width="1184" alt="Image" src="https://github.com/user-attachments/assets/ca63132c-443d-465c-bc2d-6925adcc7aef" />

<img width="1184" alt="Image" src="https://github.com/user-attachments/assets/59b9c719-a1eb-4f69-824c-d9505a7fcd50" />

**Comment by j-a-n** [comment]
Seem like a timing problem and the configuration is not ready on startup.
Please try version 4.40.3 https://raw.githubusercontent.com/j-a-n/lovelace-wallpanel/refs/heads/main/wallpanel.js

**Comment by x3n0n10** [comment]
My issue seems to have been solved in one of the recently pushed versions, thank you very much for your efforts @j-a-n ! I'm stepping out of the discussion as others seem to be having slightly other problems. Good luck guys 👍🏻

**Comment by rafareusch** [comment]
> Seem like a timing problem and the configuration is not ready on startup.
> Please try version 4.40.3 https://raw.githubusercontent.com/j-a-n/lovelace-wallpanel/refs/heads/main/wallpanel.js


Still same behavior.
Still seeing the log Wallpanel not enabled in config when I go back to the home page

**Comment by j-a-n** [comment]
I have added more logging in version 4.40.4 https://raw.githubusercontent.com/j-a-n/lovelace-wallpanel/refs/heads/main/wallpanel.js to track down the problem.
Please upgrade, reproduce the problem and post the log.

**Comment by rafareusch** [comment]
There you go

```
🖼️ Wallpanel version 4.40.4
wallpanel.js?hacstag=9795064164400:210 Wallpanel config is now: {enabled: true, enabled_on_tabs: Array(0), debug: false, wait_for_browser_mod_time: 0.25, log_level_console: 'debug', …}
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Preloading images
wallpanel.js?hacstag=9795064164400:210 Updating image 'wallpanel-screensaver-image-one' from 'https://picsum.photos/1033/919?random=1739534356'
wallpanel.js?hacstag=9795064164400:210 Location changed from 'null' to 'https://hiddennabucasaaddress.ui.nabu.casa/dashboard-wallpaneltest/home'
wallpanel.js?hacstag=9795064164400:210 Reset dashboard config
wallpanel.js?hacstag=9795064164400:210 Wallpanel config is now: {enabled: true, enabled_on_tabs: Array(0), debug: false, wait_for_browser_mod_time: 0.25, log_level_console: 'debug', …}
wallpanel.js?hacstag=9795064164400:210 activateWallpanel
wallpanel.js?hacstag=9795064164400:210 setToolbarVisibility: hideToolbar=true, hideActionItems=false
wallpanel.js?hacstag=9795064164400:210 setSidebarVisibility: hidden=false
log-message.ts:36 
        
        
       GET https://hiddennabucasaaddress.ui.nabu.casa/unknown/src/scoped-custom-element-registry.js 404 (Not Found)
(anonymous) @ stacktrace-gps.js:37
r @ stacktrace-gps.js:23
(anonymous) @ stacktrace-gps.js:218
_get @ stacktrace-gps.js:195
(anonymous) @ stacktrace-gps.js:289
findFunctionName @ stacktrace-gps.js:287
(anonymous) @ stacktrace-gps.js:272
Promise.then
(anonymous) @ stacktrace-gps.js:267
pinpoint @ stacktrace-gps.js:266
(anonymous) @ stacktrace.js:113
(anonymous) @ stacktrace.js:108
(anonymous) @ stacktrace.js:107
fromError @ stacktrace.js:105
t @ log-message.ts:36
(anonymous) @ logging-mixin.ts:48
error
hassConnected @ logging-mixin.ts:28
hassConnected @ haptic-mixin.ts:56
hassConnected @ connection-mixin.ts:221
hassConnected @ state-display-mixin.ts:10
hassConnected @ translations-mixin.ts:122
hassConnected @ themes-mixin.ts:60
hassConnected @ auth-mixin.ts:25
(anonymous) @ superPropGet.js:6
value @ home-assistant.ts:169
initializeHass @ connection-mixin.ts:216
value @ home-assistant.ts:249
await in value
value @ home-assistant.ts:103
_$AE @ reactive-element.ts:1395
performUpdate @ reactive-element.ts:1345
scheduleUpdate @ reactive-element.ts:1262
_$Ej @ reactive-element.ts:1237
await in _$Ej
requestUpdate @ reactive-element.ts:1215
_$Eu @ reactive-element.ts:950
w @ reactive-element.ts:932
S @ lit-element.ts:115
F @ hass-base-mixin.ts:6
(anonymous) @ context-mixin.ts:24
(anonymous) @ logging-mixin.ts:25
(anonymous) @ panel-title-mixin.ts:13
(anonymous) @ haptic-mixin.ts:39
(anonymous) @ url-sync-mixin.ts:18
(anonymous) @ dialog-manager-mixin.ts:29
(anonymous) @ notification-mixin.ts:6
(anonymous) @ connection-mixin.ts:40
(anonymous) @ disconnect-toast-mixin.ts:16
(anonymous) @ sidebar-mixin.ts:29
(anonymous) @ action-mixin.ts:17
(anonymous) @ more-info-mixin.ts:17
(anonymous) @ state-display-mixin.ts:7
(anonymous) @ translations-mixin.ts:75
(anonymous) @ themes-mixin.ts:24
(anonymous) @ auth-mixin.ts:15
xe @ url-sync-mixin.ts:66
(anonymous) @ quick-bar-mixin.ts:27
d @ home-assistant.ts:50
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
window.CustomElementRegistry.define @ scoped-custom-element-registry.js:85
finisher @ custom-element.ts:41
runClassFinishers @ decorate.js:172
s @ decorate.js:10
(anonymous) @ home-assistant.ts:36
(anonymous) @ app.ts:12Understand this errorAI
4wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Setup screensaver
wallpanel.js?hacstag=9795064164400:210 navigate https://hiddennabucasaaddress.ui.nabu.casa/dashboard-wallpaneltest2/0 NavigateEvent {isTrusted: true, navigationType: 'push', destination: NavigationDestination, canTransition: true, canIntercept: true, …}
wallpanel.js?hacstag=9795064164400:210 location-changed https://hiddennabucasaaddress.ui.nabu.casa/dashboard-wallpaneltest2/0 Event {isTrusted: false, detail: {…}, type: 'location-changed', target: Window, currentTarget: Window, …}
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Location changed from 'https://hiddennabucasaaddress.ui.nabu.casa/dashboard-wallpaneltest/home' to 'https://hiddennabucasaaddress.ui.nabu.casa/dashboard-wallpaneltest2/0'
wallpanel.js?hacstag=9795064164400:210 Reset dashboard config
wallpanel.js?hacstag=9795064164400:210 Location changed from 'https://hiddennabucasaaddress.ui.nabu.casa/dashboard-wallpaneltest2/0' to 'https://hiddennabucasaaddress.ui.nabu.casa/dashboard-wallpaneltest2/0'
wallpanel.js?hacstag=9795064164400:210 No wallpanel config found in dashboard config
wallpanel.js?hacstag=9795064164400:210 Wallpanel config is now: {enabled: false, enabled_on_tabs: Array(0), debug: false, wait_for_browser_mod_time: 0.25, log_level_console: 'info', …}
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 deactivateWallpanel
wallpanel.js?hacstag=9795064164400:210 setToolbarVisibility: hideToolbar=false, hideActionItems=false
wallpanel.js?hacstag=9795064164400:210 setSidebarVisibility: hidden=false
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Setup screensaver
wallpanel.js?hacstag=9795064164400:210 navigate https://hiddennabucasaaddress.ui.nabu.casa/dashboard-wallpaneltest/home NavigateEvent {isTrusted: true, navigationType: 'traverse', destination: NavigationDestination, canTransition: true, canIntercept: true, …}
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Location changed from 'https://hiddennabucasaaddress.ui.nabu.casa/dashboard-wallpaneltest2/0' to 'https://hiddennabucasaaddress.ui.nabu.casa/dashboard-wallpaneltest/home'
wallpanel.js?hacstag=9795064164400:210 Reset dashboard config
wallpanel.js?hacstag=9795064164400:210 No wallpanel config found in dashboard config
wallpanel.js?hacstag=9795064164400:210 Wallpanel config is now: {enabled: false, enabled_on_tabs: Array(0), debug: false, wait_for_browser_mod_time: 0.25, log_level_console: 'info', …}
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 deactivateWallpanel
wallpanel.js?hacstag=9795064164400:210 setToolbarVisibility: hideToolbar=false, hideActionItems=false
wallpanel.js?hacstag=9795064164400:210 setSidebarVisibility: hidden=false
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
wallpanel.js?hacstag=9795064164400:210 Update hass
wallpanel.js?hacstag=9795064164400:210 Wallpanel not enabled in config
```

**Comment by rafareusch** [comment]
@j-a-n I have a very important information...

I just found out that this issue only occurs when using the nabucasa remote url. If I'm connected locally to the server, the issue doesn't occur, at least on 4.40.0 with HA 2024.12.0.

I think with this revelation you can reproduce the issue on your end hahah

**Comment by j-a-n** [comment]
Thanks for the log and the info about nabucasa remote url.
I don't currently have a nabucasa cloud account to reproduce the issue, but I may have fixed it.
Please try version 4.40.5 https://raw.githubusercontent.com/j-a-n/lovelace-wallpanel/refs/heads/main/wallpanel.js .

**Comment by rafareusch** [comment]
> Thanks for the log and the info about nabucasa remote url. I don't currently have a nabucasa cloud account to reproduce the issue, but I may have fixed it. Please try version 4.40.5 https://raw.githubusercontent.com/j-a-n/lovelace-wallpanel/refs/heads/main/wallpanel.js .

Issue persists.

Start to see the log `Wallpanel not enabled in config` flooding when I enter the subview, and it keeps flooding after I go back to Home..

Regarding the nabucasa accound, they offer a free 1 month trial without need to fill card information, only create an account.

**Comment by j-a-n** [comment]
There is the new version 4.4.10.6 you can test: https://raw.githubusercontent.com/j-a-n/lovelace-wallpanel/refs/heads/main/wallpanel.js .

**Comment by rafareusch** [comment]
> There is the new version 4.40.6 you can test: https://raw.githubusercontent.com/j-a-n/lovelace-wallpanel/refs/heads/main/wallpanel.js .

Fantastic job, now it's fully working via nabucasa url!!

**Comment by j-a-n** [comment]
These changes are now released with version 4.41.0.
