### ISSUE TITLE
not working since v4.35.1

### ISSUE THREAD

**Issue by ManuelSteinfels** [j-a-n/lovelace-wallpanel#353]
I don't know, what did change exactly, but since version 4.35.1 the screensaver does not start running and the side panel will not be hidden. I'm running on 4.35.0 now and everything works fine. 

I first thought the new config `wait_for_browser_mod_time` (undocumented!) would do the trick, but both param guesses `true` and `false` did not help.

I even commented out all my cards, just for giving it a try, but.. 

Here is my config:
```
enabled: false
hide_toolbar: false
hide_sidebar: false
fullscreen: false
debug: false
idle_time: 10
black_screen_after_time: 0
control_reactivation_time: 1
display_time: 20000
show_progress_bar: false
show_images: true
# wait_for_browser_mod_time: true
screensaver_stop_navigation_path: /my-dashboard/home
screensaver_entity: input_boolean.wallpanel_screensaver
image_url: ${entity:sensor.wallpanel_url}
image_fit: cover
image_order: random
image_list_update_interval: 3600
info_animation_timing_function_x: ease-in-out
info_animation_timing_function_y: ease-in-out
info_move_pattern: random
info_move_interval: 120
info_move_fade_duration: 2
card_interaction: true
profile_entity: input_select.wallpanel_profile
profiles:
  user.dashboard:
    enabled: true
    enabled_on_tabs: true
    hide_sidebar: true
    fullscreen: true
  night:
    show_images: false

cards ....
```

**Comment by j-a-n** [comment]
Hi!
I don't think `wait_for_browser_mod_time` is the cause of your problems and it is documented in the README. Are there any errors in the browser console (F12)?

**Comment by zimbyzim** [comment]
Getting Similar issue with Side Bar, Seems to happen when navigating away from dashboard that has the config enabled.
This used to work as my main dashboard links to others and the full screen etc carried across.
I'll try get some time to debug, but chasing 3 kids around the house :(

**Comment by kwinne** [comment]
Hey,

I have the same issue. The issue seems to be connected when you try to enable wallpanel on a specific profile. In my case I have a "kiosk" profile that only works in local network and does not have any admin roles.  It seems @zimbyzim also works with a dashboard user, so I think its the same setup.

When I look in console, I see the error "Failed to fetch user list". I did some digging in the code and noticed there is now a call to "config/auth/list" in the setup method (Probably because the change in 4.25.1 - UserID, username and user display name can be used for user profile). 

My theory currently is that since my kiosk user has no access to that URL, the initialization fails and wallpanel does not work. 

I tested with device.KIOSK (browser mod ID) instead, and that works perfectly.

**Comment by j-a-n** [comment]
Hi @kwinne,

you are right, the error handling for the permission error was imcomplete.
Thanks!
Fixed in version 4.38.1

**Comment by ManuelSteinfels** [comment]
Perfect! Works again like a charm! Thank

**Comment by zimbyzim** [comment]
Bummer, not quite fixed for me.
Using a separate account the same way, Previously I've only had to enable the setting on 1 Dashboard and then subsequently any links from that dashaboard have the same setting applied, ie full screen side bar hidden.
Now seems I need to go through all the linked dashboards/area's and apply the settings.
Possibly by design, but just a bit more work :)
