### ISSUE TITLE
Fullscreen issue since 4.57.0

### ISSUE THREAD

**Issue by Ascendor** [j-a-n/lovelace-wallpanel#484]
First of all, thanks alot for this plugin. It allowed me to use my very old (Android 4.2.2!) tablet as a wall panel with modern features like motion detection. Awesome!

This old tablet might also be an edge case for the issue that I have: Since the tablet is so old, the only browser I was able to install that still manages to render Home Assistant, is Mozilla Fennec F-Droid in version 68.12.0.esr. When I start my dashboard with Wallpanel enabled, the browser asks for permission to use the camera for the motion detection feature. This dialog exits the fullscreen.
Of course I do allow (I have no option to save the choice), but since 4.57.0, then the fullscreen does not reappear after the dialog. Up until 4.56.1, this was not the case. After answering the dialog, fullscreen restartet. Even more: I was able to start fullscreen by tapping somewhere on an empty space of the dashboard anytime. 

I saw that you worked on the fullscreen feature in that version:

> Exit fullscreen if wallpanel is disabled (on view).

Do you see any connection? Is there a chance to get the previous behaviour together with your fix from 4.57.0? If there is no option, I can understand that, due to the edge case nature. I would then just stay downgraded.

**Comment by CSchlipp** [comment]
I'm having similar issues with Win11+current Chrome on 3 different machines. 
The browser sometimes appears to be shortly switching to fullscreen after a page refreh, but later does not switch to fullscreen anymore after interacting with the dashboard. 
I currently work around this issue by enabling fullscreen "manually" using a plugin.

**Comment by j-a-n** [comment]
The update to 4.58.0 brings back the old behavior unless you explicitly set `keep_fullscreen` to `false`.

**Comment by Ascendor** [comment]
Wow, thanks so much for the quick response. I'll try it out right away.

Do you accept donations?

**Comment by Ascendor** [comment]
@j-a-n,  no luck on my side. Still, only 4.56.1 works. I've tried 4.58.0 with unchanged config, then with keep_fullscreen true, then with keep_fullscreen false. All to no avail.

(I've killed browser caches before trying)

**Comment by j-a-n** [comment]
This should be resolved in version 4.58.1.

**Comment by CSchlipp** [comment]
Issue seems to be fixed for me in 4.58.1, thanks a lot!

**Comment by Ascendor** [comment]
@j-a-n, unfortunately still no luck on my end. I guess it's my old browser then and I just have to stay with 4.56.1, right?

**Comment by j-a-n** [comment]
Yes, unfortunately it is sometimes not possible to support all old browsers.
